---
title: "G3viz: figure and supplementary"
author: "Xin Guo <g3viz.group at gmail.com>"
date: "2019-04-01"
output:
  html_document:
    df_print: kable
    highlight: tango
    number_sections: no
    theme: lumen
    toc: no
    toc_depth: 2
    toc_float:
      collapsed: no
      smooth_scroll: yes
vignette: >
  %\VignetteEncoding{utf8}
  %\VignetteIndexEntry{G3viz: chart themes}
  %\VignetteEngine{knitr::rmarkdown}
---

```{r, message=FALSE, include = FALSE}
# install package
library(g3viz)
library(cgdsr)
library(knitr)
```


```{r setup, include = FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	collapse = TRUE,
	comment = "#>"
)
```


# Figure 1
```{r, include = TRUE, message=FALSE}
# Retrieve TP53 mutation data of the MSK-IMPACT study from cBioPortal
mutation.dat <- getMutationsFromCbioportal("msk_impact_2017", "TP53")

# Using “nature2” chart theme
chart.options <- g3Lollipop.theme(theme.name = "nature2",
                                  title.text = "TP53 gene mutation (MSK-IMPACT study)",
                                  y.axis.label = "# of TP53 Mutations",
                                  legend.title = "Mutation Class")

# Generate g3viz lollipop-diagram
g3Lollipop(mutation.dat,
           gene.symbol = "TP53",
           btn.style = "blue", # built-in blue-style output buttons
           plot.options = chart.options,
           output.filename = "g3lollipop")
```
