language: r
sudo: false
cache: packages

install:
- R -e 'install.packages(c("jsonlite", "cBioPortalData", "stringr", "htmlwidgets", "knitr", "rmarkdown", "kableExtra", "shiny"))'

script:
- R CMD build .
- R CMD check *tar.gz
